# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: sensormonitoring build and test

on:
  workflow_dispatch:
    # This event allows manual triggering
  push:
    branches: [ "master" ]
    paths:
    - '**.cs'
    - '**.csproj'
  pull_request:
    branches: [ "master" ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '6.0.100' # The .NET SDK version to use

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Change directory to test project
      run: cd tests/ApiTests
    - name: Restore dependencies for test project
      run: dotnet restore
    - name: Change directory to main solution
      run: cd ../..
    - name: Restore dependencies for main solution
      run: dotnet restore
    - name: Build main solution
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
